### ISSUE TITLE
Training the model on your inpainting dataset

### ISSUE THREAD

**Issue by SherryXTChen** [HighwayWu/InpaintingForensics#4]
Hi, Thank you for sharing your work. I have been training your model from start (no pretrained weight was used) using your inpainting dataset and during training there is minimal change on the gen_loss and auc score. Specifically, I get gen_loss around 13-14 and auc score fixed at 0.5 (50%), which seems to suggest that the model has no discrimination capacity. I have trained the model for several epoches and these numbers stay consistent, is there something I should change to resolve this issue? Thanks in advance!

**Comment by HighwayWu** [comment]
Hi, thanks for your interest. Actually, the dataset I shared is only for testing, rather than training. It would be better to use your own training data for the training.
