### ISSUE TITLE
About the training set

### ISSUE THREAD

**Issue by flyywh** [HighwayWu/InpaintingForensics#5]
I am wondering whether the authors can provide the training set of the paper?
If it is possible, it is also welcomed to provide a copy of Dresden Image Database, as the link (http://forensics.inf.tu-dresden.de/ddimgdb/locations) has been invalid.

**Comment by HighwayWu** [comment]
Thank you for your interest. We'll release the training set in the following week, but we have no authority to redistribute the Dresden data. Please contact the original authors.
