### ISSUE TITLE
MacOS issue

### ISSUE THREAD

**Issue by under-score** [HighwayWu/InpaintingForensics#6]
I have some problems to run it on Big Sur (11.6.) as there is [no CUDA support](https://docs.nvidia.com/cuda/archive/9.2/cuda-installation-guide-mac-os-x/index.html)

`AssertionError: Torch not compiled with CUDA enabled`

Do I just have to wait [another 4 months for official support](https://stackoverflow.com/questions/63423463/using-pytorch-cuda-on-macbook-pro) or do I have[ to buy some extra eGPU hardware](https://support.apple.com/en-us/HT208544)?

Tried to rewrite your demo to Google Colabs (where we have GPU support) but also here is a CUDA error

![xxx](https://user-images.githubusercontent.com/2796454/146889688-49d14faf-19eb-43cc-98a5-9c152425916a.jpg)

**Comment by HighwayWu** [comment]
Sorry that I'm not familiar with the MacOS.

For the Google Colabs error, it seems that the script can't load the data from GPU to CPU.

**Comment by under-score** [comment]
thank you - great project.

**Comment by SreelakshmyJayaram** [comment]
@under-score How did you solve this google colab issue? could you please describe what change did you do in the code?

**Comment by under-score** [comment]
Went to a high performance cluster. If this is not an option for you - search for "Jetson Nano" or "Google Coral".

**Comment by SreelakshmyJayaram** [comment]
thank you for your quick response :)
